policy:
  type: pi05
  pretrained_path: lerobot/pi05_base
  device: cuda
  push_to_hub: false
  state_cond: false

dataset:
  repo_id: <your dataset repository id>
  video_backend: torchcodec
  use_imagenet_stats: true

wandb:
  enable: true
  disable_artifact: true
  project: lerobot

num_workers: 8
batch_size: 8
steps: 50000
seed: 42

output_dir: outputs/train/pi05_async_libero
job_name: pi05_async_libero

use_policy_training_preset: false
optimizer:
  type: adamw
  lr: 5.0e-5
  betas: [0.9, 0.95]
  weight_decay: 0.0
  grad_clip_norm: 1.0

scheduler:
  type: cosine_decay_with_warmup
  num_warmup_steps: 1000
  num_decay_steps: 50000
  peak_lr: 5.0e-5
  decay_lr: 5.0e-6

save_checkpoint: true
save_freq: 10000
log_freq: 200

max_delay_steps: 4

shared_observation: false
