# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vlash.transport import services_pb2 as vlash_dot_transport_dot_services__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vlash/transport/services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LaunchInference = channel.stream_unary(
                '/transport.RemoteInference/LaunchInference',
                request_serializer=vlash_dot_transport_dot_services__pb2.Observation.SerializeToString,
                response_deserializer=vlash_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.GetActionChunk = channel.unary_unary(
                '/transport.RemoteInference/GetActionChunk',
                request_serializer=vlash_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=vlash_dot_transport_dot_services__pb2.ActionChunk.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/transport.RemoteInference/Ready',
                request_serializer=vlash_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=vlash_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)


class RemoteInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LaunchInference(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LaunchInference': grpc.stream_unary_rpc_method_handler(
                    servicer.LaunchInference,
                    request_deserializer=vlash_dot_transport_dot_services__pb2.Observation.FromString,
                    response_serializer=vlash_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'GetActionChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionChunk,
                    request_deserializer=vlash_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=vlash_dot_transport_dot_services__pb2.ActionChunk.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=vlash_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=vlash_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.RemoteInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transport.RemoteInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LaunchInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/transport.RemoteInference/LaunchInference',
            vlash_dot_transport_dot_services__pb2.Observation.SerializeToString,
            vlash_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActionChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.RemoteInference/GetActionChunk',
            vlash_dot_transport_dot_services__pb2.Empty.SerializeToString,
            vlash_dot_transport_dot_services__pb2.ActionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.RemoteInference/Ready',
            vlash_dot_transport_dot_services__pb2.Empty.SerializeToString,
            vlash_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
